### ISSUE TITLE
sqlite3

### ISSUE THREAD

**Issue by hanfengsunshine** [carryme9527/poetry_analyzer#1]
![image](https://cloud.githubusercontent.com/assets/14012055/25807381/39022120-3439-11e7-8db1-7d835e2b5d81.png)
 请问 我已经将cdbd_sqlite.db 放在data 目录下，已经安装了gensim和thulac， 为何报错呢？
BIOG MAIN 已经是table了呀 
 
![image](https://cloud.githubusercontent.com/assets/14012055/25807461/7dd55cd6-3439-11e7-8d0c-9b81998423a1.png)
 可以留个联系方式？ 谢谢

**Comment by carryme9527** [comment]
我認為應該是 Linux / Windows 路徑分隔符號不同所造成的。
Linux 用 data/cbdb_sqlite.db
Windows 用 data\cbdb_sqlite.db
我改一下 argparse 預設值指定的方式

**Comment by carryme9527** [comment]
pull and try again. if it worked, please close this issue.
Thanks.

**Comment by hanfengsunshine** [comment]
![fqo ri 7 j2uuthv 475](https://cloud.githubusercontent.com/assets/14012055/25902223/9003b784-35cb-11e7-82cd-d299264bdfd3.png)
Hi 
我运行成功了。是否应该去thulac 下载training model ?谢谢！

**Comment by carryme9527** [comment]
看起來是這行
https://github.com/carryme9527/fork.poetry_analyzer/blob/python2/word_level_analyzer.py#L158
要呼叫下面這個function
https://github.com/carryme9527/fork.poetry_analyzer/blob/python2/word_level_analyzer.py#L71
但是卻呼叫到gensim的word2vec了
你試著把這兩個地方的function名字換掉看有沒有問題？
